### ISSUE TITLE
Normal (non-block) strings can count as comments

### ISSUE THREAD

**Issue by ThanGerlek** [softwareconstruction240/checkstyle#2]
The line `String allFilesRegex = "/*";` gets flagged as "commented out code".

**Comment by 19mdavenport** [comment]
Yeah, I've know about this for a while. In fact, the commented out code check, when run on it's own source code, finds commented out code that isn't there. I haven't been super worried about it since it hasn't been a problem until now. Do you have any suggestions how to fix it? I've thought about it a bit, and a regex may help here; I just want to make sure it is able to distinguish between `/*` in a string vs. as the start of a block comment and doesn't undercount commented out code.

@frozenfrank your regex experience may be helpful here, do you have any ideas?
